// 오늘의 명언 - 내장 명언 목록 (한국어)
// 각 명언은 cat(카테고리)으로 분류됩니다: "success"(성공·일) / "challenge"(도전·인내) / "life"(삶·철학)
// 매일 각 카테고리에서 1개씩, 총 3개가 날짜 기준으로 결정적으로 선택됩니다.
const QUOTES = [
  // ── 도전 · 인내 (challenge) ──
  { text: "오늘 걷지 않으면 내일은 뛰어야 한다.", author: "작자 미상", cat: "challenge" },
  { text: "가장 큰 위험은 위험 없는 삶이다.", author: "스티븐 코비", cat: "challenge" },
  { text: "천 리 길도 한 걸음부터.", author: "노자", cat: "challenge" },
  { text: "당신이 할 수 있다고 믿든 할 수 없다고 믿든, 믿는 대로 될 것이다.", author: "헨리 포드", cat: "challenge" },
  { text: "시작이 반이다.", author: "아리스토텔레스", cat: "challenge" },
  { text: "실패는 성공의 어머니다.", author: "작자 미상", cat: "challenge" },
  { text: "꿈을 밀고 나가는 힘은 이성이 아니라 희망이며, 두뇌가 아니라 심장이다.", author: "도스토옙스키", cat: "challenge" },
  { text: "포기하지 마라. 지금 이 순간이 가장 힘든 순간이 아닐 수도 있다.", author: "작자 미상", cat: "challenge" },
  { text: "할 수 있다고 생각하는 사람이 결국 해내는 사람이다.", author: "작자 미상", cat: "challenge" },
  { text: "가장 어두운 밤도 언젠가는 끝나고 해는 떠오른다.", author: "빅토르 위고", cat: "challenge" },
  { text: "고통이 없으면 얻는 것도 없다.", author: "벤저민 프랭클린", cat: "challenge" },
  { text: "느리게 가는 것을 두려워하지 말고, 멈춰 서는 것을 두려워하라.", author: "중국 속담", cat: "challenge" },
  { text: "노력은 배신하지 않는다.", author: "작자 미상", cat: "challenge" },
  { text: "지금 하지 않으면 언제 하겠는가.", author: "작자 미상", cat: "challenge" },
  { text: "실패란 넘어지는 것이 아니라 넘어진 자리에 머무는 것이다.", author: "작자 미상", cat: "challenge" },
  { text: "가장 큰 영광은 결코 넘어지지 않는 데 있는 것이 아니라 넘어질 때마다 일어서는 데 있다.", author: "공자", cat: "challenge" },
  { text: "위대함은 남보다 앞서가는 데 있지 않다. 어제의 나보다 앞서가는 데 있다.", author: "힌두 속담", cat: "challenge" },
  { text: "미래는 자신의 꿈의 아름다움을 믿는 사람들의 것이다.", author: "엘리너 루스벨트", cat: "challenge" },
  { text: "할 수 있다고 믿어라. 그러면 이미 절반은 이룬 것이다.", author: "시어도어 루스벨트", cat: "challenge" },
  { text: "삶이 있는 한 희망은 있다.", author: "키케로", cat: "challenge" },
  { text: "실수를 두려워하지 마라. 실수하지 않는 유일한 방법은 아무것도 하지 않는 것이다.", author: "작자 미상", cat: "challenge" },
  { text: "당신이 포기할 때, 나는 시작한다.", author: "정주영", cat: "challenge" },
  { text: "길이 없으면 길을 만들며 간다.", author: "정주영", cat: "challenge" },
  { text: "한 번의 실패와 영원한 실패를 혼동하지 마라.", author: "F. 스콧 피츠제럴드", cat: "challenge" },
  { text: "나는 매일 아침 스스로에게 말한다. 오늘은 어제보다 나은 하루가 될 것이라고.", author: "작자 미상", cat: "challenge" },
  { text: "꽃이 피지 않으면 환경을 바꿔라. 꽃이 아니라 환경을 탓하라.", author: "알렉산더 덴 헤이어", cat: "challenge" },
  { text: "당신이 상상할 수 있다면, 그것을 이룰 수 있다.", author: "월트 디즈니", cat: "challenge" },
  { text: "우리가 두려워해야 할 것은 두려움 그 자체뿐이다.", author: "프랭클린 루스벨트", cat: "challenge" },
  { text: "인내는 쓰지만 그 열매는 달다.", author: "장 자크 루소", cat: "challenge" },
  { text: "노력하는 사람에게 불가능이란 없다.", author: "나폴레옹", cat: "challenge" },
  { text: "가장 좋은 시절은 아직 오지 않았다.", author: "로버트 브라우닝", cat: "challenge" },
  { text: "우리는 넘어지기 위해서가 아니라 일어서기 위해 태어났다.", author: "작자 미상", cat: "challenge" },
  { text: "가장 큰 모험은 자기 자신답게 사는 것이다.", author: "작자 미상", cat: "challenge" },

  // ── 성공 · 일 (success) ──
  { text: "성공은 최종적인 것이 아니고, 실패는 치명적인 것이 아니다. 중요한 것은 계속하는 용기다.", author: "윈스턴 처칠", cat: "success" },
  { text: "위대한 일을 하는 유일한 방법은 자신이 하는 일을 사랑하는 것이다.", author: "스티브 잡스", cat: "success" },
  { text: "행동은 모든 성공의 기초적인 열쇠다.", author: "파블로 피카소", cat: "success" },
  { text: "작은 기회로부터 종종 위대한 업적이 시작된다.", author: "데모스테네스", cat: "success" },
  { text: "가장 유능한 사람은 가장 배우기에 힘쓰는 사람이다.", author: "괴테", cat: "success" },
  { text: "성공의 비결은 목적을 향해 흔들리지 않는 것이다.", author: "벤저민 디즈레일리", cat: "success" },
  { text: "지혜로운 사람은 기회를 찾는 대신 기회를 만든다.", author: "프랜시스 베이컨", cat: "success" },
  { text: "어려움 한가운데에 기회가 있다.", author: "알베르트 아인슈타인", cat: "success" },
  { text: "성공한 사람이 되려 하기보다 가치 있는 사람이 되려고 힘써라.", author: "알베르트 아인슈타인", cat: "success" },
  { text: "당신이 하는 일에 최선을 다하면, 그 일이 당신을 성공으로 이끈다.", author: "작자 미상", cat: "success" },
  { text: "기회는 준비된 자에게 온다.", author: "루이 파스퇴르", cat: "success" },
  { text: "성공은 열정을 잃지 않고 실패를 거듭할 수 있는 능력이다.", author: "윈스턴 처칠", cat: "success" },
  { text: "행운은 노력이 기회를 만났을 때 생긴다.", author: "세네카", cat: "success" },
  { text: "위대한 성취는 대개 큰 위험을 감수한 결과다.", author: "헤로도토스", cat: "success" },
  { text: "꿈을 이루는 가장 좋은 방법은 잠에서 깨어나는 것이다.", author: "폴 발레리", cat: "success" },
  { text: "당신의 일을 사랑하되, 그 일이 당신을 사랑하도록 두지는 마라.", author: "작자 미상", cat: "success" },
  { text: "지금 시작하라. 완벽한 때는 결코 오지 않는다.", author: "나폴레온 힐", cat: "success" },
  { text: "성공의 크기는 당신이 극복한 장애물의 크기로 결정된다.", author: "부커 워싱턴", cat: "success" },
  { text: "재능은 게임을 이기게 하지만, 팀워크와 지성은 우승을 안겨준다.", author: "마이클 조던", cat: "success" },
  { text: "나는 실패한 것이 아니다. 잘 안 되는 방법 1만 가지를 발견했을 뿐이다.", author: "토머스 에디슨", cat: "success" },
  { text: "성공이란 열정을 가지고 자신이 좋아하는 일을 하며 사는 것이다.", author: "작자 미상", cat: "success" },
  { text: "느리더라도 멈추지 않는 한 문제가 되지 않는다.", author: "공자", cat: "success" },
  { text: "목표가 없는 노력은 방향이 없는 항해와 같다.", author: "작자 미상", cat: "success" },
  { text: "일을 미루는 것은 시간을 훔치는 도둑이다.", author: "에드워드 영", cat: "success" },
  { text: "성공으로 가는 엘리베이터는 고장 났다. 계단을 이용하라. 한 계단씩.", author: "조 지라드", cat: "success" },
  { text: "당신이 오를 수 있는 가장 높은 곳은 스스로 정한 한계다.", author: "작자 미상", cat: "success" },
  { text: "탁월함은 습관이다. 우리는 반복하는 행동으로 만들어진다.", author: "아리스토텔레스", cat: "success" },
  { text: "성공은 매일 반복한 작은 노력들의 합이다.", author: "로버트 콜리어", cat: "success" },
  { text: "기회를 놓치지 않는 사람이 아니라, 기회를 만드는 사람이 되어라.", author: "조지 버나드 쇼", cat: "success" },
  { text: "능력은 당신이 무엇을 할 수 있는지 결정하고, 동기는 당신이 무엇을 하는지 결정한다.", author: "루 홀츠", cat: "success" },
  { text: "가장 큰 위험은 아무 위험도 감수하지 않는 것이다.", author: "마크 저커버그", cat: "success" },
  { text: "지식에 투자하는 것이 가장 높은 이자를 준다.", author: "벤저민 프랭클린", cat: "success" },
  { text: "성공한 사람과 실패한 사람의 차이는 의지력의 차이다.", author: "빈스 롬바르디", cat: "success" },
  { text: "꿈의 크기가 그 사람의 크기를 결정한다.", author: "작자 미상", cat: "success" },
  { text: "당신이 포기하는 순간이 바로 성공하기 직전일 수 있다.", author: "작자 미상", cat: "success" },
  { text: "행동하는 자만이 결과를 얻는다.", author: "레오나르도 다 빈치", cat: "success" },
  { text: "오늘 하지 않으면 내일도 하지 않을 것이다.", author: "작자 미상", cat: "success" },
  { text: "성공은 준비, 노력, 그리고 실패로부터 배우는 것으로 이루어진다.", author: "콜린 파월", cat: "success" },
  { text: "오늘 할 수 있는 일에 전력을 다하라.", author: "아이작 뉴턴", cat: "success" },

  // ── 삶 · 철학 (life) ──
  { text: "행복은 습관이다. 그것을 몸에 지니라.", author: "허버드", cat: "life" },
  { text: "인생은 자전거를 타는 것과 같다. 균형을 잡으려면 계속 움직여야 한다.", author: "알베르트 아인슈타인", cat: "life" },
  { text: "어제는 역사이고, 내일은 미스터리이며, 오늘은 선물이다.", author: "엘리너 루스벨트", cat: "life" },
  { text: "당신의 시간은 한정되어 있다. 그러니 다른 사람의 삶을 사느라 낭비하지 마라.", author: "스티브 잡스", cat: "life" },
  { text: "생각을 조심하라, 말이 된다. 말을 조심하라, 행동이 된다.", author: "마거릿 대처", cat: "life" },
  { text: "배움에는 끝이 없다.", author: "작자 미상", cat: "life" },
  { text: "오르막이 있으면 내리막도 있다.", author: "작자 미상", cat: "life" },
  { text: "행복은 목적지가 아니라 여행하는 방법이다.", author: "마거릿 리 런벡", cat: "life" },
  { text: "당신이 세상에서 보고 싶은 변화, 그 자체가 되어라.", author: "마하트마 간디", cat: "life" },
  { text: "오늘의 나는 어제의 내 생각들로 만들어졌다.", author: "부처", cat: "life" },
  { text: "검토하지 않는 삶은 살 가치가 없다.", author: "소크라테스", cat: "life" },
  { text: "인생은 우리에게 일어나는 일 10%와 그것에 반응하는 방식 90%로 이루어진다.", author: "찰스 스윈돌", cat: "life" },
  { text: "삶이 있는 한 배움은 계속된다.", author: "세네카", cat: "life" },
  { text: "우리는 우리가 반복적으로 하는 것의 결과다.", author: "아리스토텔레스", cat: "life" },
  { text: "행복은 소유가 아니라 존재의 문제다.", author: "에리히 프롬", cat: "life" },
  { text: "죽음을 기억하라. 그것이 삶을 온전히 살게 한다.", author: "마르쿠스 아우렐리우스", cat: "life" },
  { text: "인생은 가까이서 보면 비극이지만 멀리서 보면 희극이다.", author: "찰리 채플린", cat: "life" },
  { text: "우리가 통제할 수 있는 것은 우리의 생각과 행동뿐이다.", author: "에픽테토스", cat: "life" },
  { text: "삶의 의미는 의미를 부여하는 데 있다.", author: "작자 미상", cat: "life" },
  { text: "고요한 물이 깊이 흐른다.", author: "라틴 속담", cat: "life" },
  { text: "당신이 어둠을 두려워하는 만큼, 어둠도 당신의 빛을 두려워한다.", author: "작자 미상", cat: "life" },
  { text: "타인을 아는 것은 지혜이고, 자신을 아는 것은 깨달음이다.", author: "노자", cat: "life" },
  { text: "가진 것에 만족하는 사람이 진정한 부자다.", author: "노자", cat: "life" },
  { text: "인생은 자신을 찾는 것이 아니라 자신을 만드는 것이다.", author: "조지 버나드 쇼", cat: "life" },
  { text: "현재에 충실하라. 지금 이 순간이 당신이 가진 전부다.", author: "에크하르트 톨레", cat: "life" },
  { text: "산다는 것은 세상에서 가장 드문 일이다. 대부분의 사람은 그저 존재할 뿐이다.", author: "오스카 와일드", cat: "life" },
  { text: "행복으로 가는 길은 없다. 행복이 곧 길이다.", author: "틱낫한", cat: "life" },
  { text: "바꿀 수 없는 것은 받아들이고, 바꿀 수 있는 것은 바꿀 용기를 가져라.", author: "라인홀트 니부어", cat: "life" },
  { text: "고통은 피할 수 없지만, 괴로움은 선택이다.", author: "무라카미 하루키", cat: "life" },
  { text: "삶은 소유하는 것이 아니라 경험하는 것이다.", author: "작자 미상", cat: "life" },
  { text: "완벽한 삶이란 없다. 다만 완벽하게 살려는 마음이 있을 뿐이다.", author: "작자 미상", cat: "life" },
  { text: "인간은 자유롭도록 선고받았다.", author: "장 폴 사르트르", cat: "life" },
  { text: "지혜의 시작은 무지를 인정하는 것이다.", author: "소크라테스", cat: "life" },
  { text: "당신의 삶을 바꾸고 싶다면, 지금 당장 시작하라. 화려하게 하려 하지 말고.", author: "윌리엄 제임스", cat: "life" },
  { text: "모든 것은 지나간다. 좋은 날도, 나쁜 날도.", author: "작자 미상", cat: "life" },
  { text: "행복은 스스로 만족할 줄 아는 사람의 것이다.", author: "아리스토텔레스", cat: "life" },
  { text: "삶을 사랑한다면 시간을 낭비하지 마라. 삶은 시간으로 이루어져 있으니.", author: "벤저민 프랭클린", cat: "life" },
  { text: "마음이 평온하면 온 세상이 평온하다.", author: "장자", cat: "life" }
];

// 카테고리 메타데이터 (표시 순서 = 오늘의 명언 카드 순서)
const CATEGORIES = [
  { id: "success", label: "성공·일" },
  { id: "challenge", label: "도전·인내" },
  { id: "life", label: "삶·철학" }
];

if (typeof module !== "undefined") module.exports = { QUOTES, CATEGORIES };
